import type { Metadata } from "next";
import "./globals.css";
import AnimatedBackground from "@/components/ui/AnimatedBackground";


export const metadata: Metadata = {
  title: "Rakshit Garg-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AnimatedBackground>{children}</AnimatedBackground>
      </body>
    </html>
  );
}
